# Generated by Django 4.1.2 on 2022-10-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-created'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='update',
        ),
        migrations.AddField(
            model_name='noticia',
            name='updated',
            field=models.TimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='created',
            field=models.TimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='image',
            field=models.ImageField(upload_to='noticias', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
